spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration;
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration;

eureka:
  cloud:
    discovery:
      enabled: false
