server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sgalmeid/ValidationConfig
          search-paths:
            - flightservice
            - pilotservice
            - cityservice


