FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait
CMD /wait && java -jar /app.jar --server.port=8080
#ENTRYPOINT ["wait","java","-jar","/app.jar", "--server.port=8080"]