server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#spring:
#  datasource:
#    hikari:
#      connectionTimeout: 20000
#      maximumPoolSize: 5
#    url: jdbc:postgresql://localhost:5432/flights
#    username: sga
#    password: sga
#  jpa:
#    hibernate:
#      ddl-auto: create
